# Generated by Django 4.2.5 on 2023-09-29 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments_likes_alter_comments_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 20, 53, 34, 665737, tzinfo=datetime.timezone.utc)),
        ),
    ]
