# Generated by Django 4.2.5 on 2023-09-29 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comments_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 21, 23, 54, 867996, tzinfo=datetime.timezone.utc)),
        ),
    ]
