# Generated by Django 4.2.5 on 2023-10-02 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comments_create_date_remove_comments_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 19, 47, 31, 515608, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
